blogs/urls.py
# @Time    : 18-6-5 下午2:19
# @Author  : wengwenyu
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from .views import index, list1, Search, detail

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^list/$',list1, name='list1'),
    url(r'^search/$', Search.as_view(),name='search'),
    url(r'^tags/(?P<tid>\d*)/$', list1, name='tags'),
    url(r'^cat/(?P<cid>\d*)/$', list1, name='cat'),
    url(r'^detail/(?P<pid>\d*)/$', detail, name='detail'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blogs import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls, namespace='blog'))
]

blogs/models.py
from django.db import models
from users.models import BlogUser
from datetime import datetime


class Banner(models.Model):
    title = models.CharField(verbose_name='标题', max_length=50)
    cover = models.ImageField(verbose_name='轮播图', upload_to='static/images/banner')
    link_url = models.URLField(max_length=150, verbose_name='图片链接')
    idx = models.IntegerField(verbose_name='索引')
    is_active = models.BooleanField(verbose_name='是否激活', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name


class BlogCategory(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name


class Tags(models.Model):
    name = models.CharField(verbose_name='标签', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Post(models.Model):
    user = models.ForeignKey(BlogUser, verbose_name='作者')
    category = models.ForeignKey(BlogCategory, verbose_name='博客分类', default=None)
    tags = models.ManyToManyField(Tags, verbose_name='标签')
    title = models.CharField(verbose_name='标题', max_length=30, null=False)
    content = models.CharField(verbose_name='内容', max_length=4000, null=False)
    pub_date = models.DateTimeField(verbose_name='发布时间', default=datetime.now)
    cover = models.ImageField(verbose_name='博客封面', upload_to='static/image/post', default=None)
    views = models.IntegerField(verbose_name='浏览量')
    is_recomment = models.BooleanField(verbose_name='是否推荐博客', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name


class Comment(models.Model):
    user = models.ForeignKey(BlogUser, verbose_name='评论者')
    post = models.ForeignKey(Post, verbose_name='博客')
    content = models.CharField(verbose_name='评论内容', max_length=400)
    pub_date = models.DateTimeField(verbose_name='发布时间', default=datetime.now)

    def __str__(self):
        return self.post.title

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name


class FriendlyLink(models.Model):
    title = models.CharField(max_length=30, verbose_name='友情链接标题')
    link = models.URLField(max_length=150, verbose_name='链接地址', default=None)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.
class BlogUser(AbstractUser):
    nikename = models.CharField(max_length=30, default='', verbose_name='昵称')


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=50, verbose_name='验证码', default='')
    eamil = models.CharField(max_length=30, verbose_name='邮箱')
    send_type = models.CharField(max_length=30, verbose_name='验证码类型',
                                 choices=(('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')))
    send_time = models.DateTimeField(verbose_name='发送时间', default=datetime.now)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.eamil

blogs/views.py
from django.shortcuts import render
from .models import Banner, Post, Comment, FriendlyLink, BlogCategory, Tags
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage
from django.views.generic.base import View
from django.db.models import Q


def detail(request, pid):
    vieww = Post.objects.get(id=pid)
    vieww.views+=1
    vieww.save()
    tags_list = vieww.tags
    about_recomment = []
    for tag in tags_list.all():
        about_recomment.extend(tag.post_set.all())
    comment_list = Comment.objects.order_by('-pub_date')
    comment_list2 = []
    for piw in comment_list:
        if piw.post not in comment_list2:
            comment_list2.append(piw.post)
    cds = {
        'views':vieww,
        'about_recomment':about_recomment,
        'comment_list': comment_list2,
    }
    return render(request,'show.html', cds)



class Search(View):
    def get(self, request):
        pass

    def post(self, request):
        keywords = request.POST.get('keyword')
        postlist = Post.objects.filter(Q(title__contains=keywords) | Q(content__contains=keywords))
        tags = Tags.objects.all()
        comment_list = Comment.objects.order_by('-pub_date')
        comment_list2 = []
        for piw in comment_list:
            if piw.post not in comment_list2:
                comment_list2.append(piw.post)
        try:
            page = request.GET.get('page', 1)
        except:
            page = 1

        # objects = ['john', 'edward', 'josh', 'frank']
        p = Paginator(postlist, per_page=2, request=request)

        people = p.page(page)
        cdx = {
            'postlist': postlist,
            'people':people,
            'tags_list': tags,
            'comment_list': comment_list2,
        }
        return render(request, 'list.html', cdx)


# Create your views here.
def index(request):
    #所有post
    banner_list = Banner.objects.all()
    #倒序post
    banner_filter3 = Post.objects.order_by('-pub_date')
    #推荐
    banner_filter = Post.objects.filter(is_recomment=True)
    #评论
    comment_list = Comment.objects.order_by('-pub_date')
    comment_list2 = []

    try:
        page = request.GET.get('page', 1)
    except:
        page = 1

    # objects = ['john', 'edward', 'josh', 'frank']
    p = Paginator(banner_filter3, per_page=2, request=request)

    people = p.page(page)
    for i in banner_filter3:
        i.content = i.content[:20]
    for i2 in banner_filter:
        i2.content = i2.content[:20]
    for piw in comment_list:
        if piw.post not in comment_list2:
            comment_list2.append(piw.post)
    friendlylink_list = FriendlyLink.objects.all()
    blogcategory_list = BlogCategory.objects.all()
    ctx = {
        'people':people,
        'banner_list': banner_list,
        'banner_filter2': banner_filter,
        'banner_filter3': banner_filter3,
        'comment_list': comment_list2,
        'friendlylink_list': friendlylink_list,
        'blogcategory_list': blogcategory_list,
    }
    return render(request, 'index.html', ctx)


def list1(request, tid=-1, cid = -1):
    if tid != -1:
        Post1 = Post.objects.filter(tags=tid)
    elif cid != -1:
        Post1 = Post.objects.filter(category=cid)
    else:
        Post1 = Post.objects.order_by('-pub_date')
    comment_list = Comment.objects.order_by('-pub_date')
    comment_list2 = []
    tags = Tags.objects.all()
    for po in Post1:
        po.content = po.content[:20]
    for piw in comment_list:
        if piw.post not in comment_list2:
            comment_list2.append(piw.post)
    try:
        page = request.GET.get('page', 1)
    except:
        page = 1

    # objects = ['john', 'edward', 'josh', 'frank']
    p = Paginator(Post1, per_page=2, request=request)

    people = p.page(page)
    cdd = {
        'postlist': Post1,
        'comment_list': comment_list2,
        'people': people,
        'tags_list': tags,
    }
    return render(request, 'list.html', cdd)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>知奇博客首页</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nprogress.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/icon.png' %}/static/images/icon.png">
    <link rel="shortcut icon" href="">

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/nprogress.js' %}"></script>
    <script src="{% static 'js/jquery.lazyload.min.js' %}"></script>

</head>
<body class="user-select">
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="header-topbar hidden-xs link-border">
                <ul class="site-nav topmenu">
                    <li><a href="#">标签云</a></li>
                    <li><a href="#" rel="nofollow">读者墙</a></li>
                    <li><a href="#" title="RSS订阅">
                        <i class="fa fa-rss">
                        </i> RSS订阅
                    </a></li>
                </ul>
                爱学习 更爱分享
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#header-navbar" aria-expanded="false"><span class="sr-only"></span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                <h1 class="logo hvr-bounce-in"><a href="#" title="知奇课堂博客"><img
                        src="/static/images/201610171329086541.png"
                        alt="知奇课堂博客"></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <form class="navbar-form visible-xs" action="/Search" method="post">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20"
                               autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span></div>
                </form>

                <ul class="nav navbar-nav navbar-left">
                    <li><a data-cont="知奇课堂博客" title="知奇课堂博客" href="{% url 'blog:index' %}">首页</a></li>
                    <li><a data-cont="列表页" title="列表页" href="{% url 'blog:list1' %}">列表页</a></li>
{#                    <li><a data-cont="详细页" title="详细页" href="{% url 'blog:detail' %}">详细页</a></li>#}
{#                    <li><a data-cont="404" title="404" href="404.html">404</a></li>#}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a data-cont="登录" title="登录" href="#">登录</a></li>
                    <li><a data-cont="注册" title="注册" href="#">注册</a></li>
                </ul>

            </div>
        </div>
    </nav>
</header>
{% block content %}

{% endblock content %}

<footer class="footer">
    <div class="container">
        <p>Copyright &copy; 2016.Company name All rights reserved.</p>
    </div>
    <div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'js/jquery.ias.js' %}"></script>#}
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/page.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; 上一页</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; 上一页</span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">下一个 &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">下一页 &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

templates/serach.html
<form class="navbar-form" action="{% url 'blog:search' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                               maxlength="15" autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span></div>
                </form>